"""Phase C2: exact full-lexicon RSA over all 437,207,235 unique word pairs.

Question: is the ventral geometry more semantic or more phonological, and is the
dorsal geometry more phonological or more semantic?

Distances, all on the upper triangle j > i of the 29,571-word lexicon:

    D_LTM   (i,j) = 1 - cosine(s_hat_i,  s_hat_j)      per seed
    D_WM    (i,j) = 1 - cosine(h_WM_i,   h_WM_j)       per seed
    D_GloVe (i,j) = 1 - cosine(GloVe_i,  GloVe_j)
    D_phon  (i,j) = Levenshtein(phonemes_i, phonemes_j)   raw, PRIMARY
    D_phonN (i,j) = Levenshtein / max(len_i, len_j)        normalised, sensitivity

Phoneme sequences are the lexical ARPABET forms only: no BOS, no EOS, no PAD.
Identical forms therefore have distance 0 by construction.

**No dense 29,571 x 29,571 matrix is ever materialised.**  The upper triangle is
streamed in row blocks; for each block the seven distance vectors are formed,
masked to j > i, and folded into exact sufficient statistics (count, per-variable
sums, and the full cross-product matrix) accumulated in float64.  Every reported
correlation is therefore exact over all 437,207,235 pairs, not a sample.

Levenshtein uses rapidfuzz.process.cdist (already installed; no new dependency),
verified against a reference DP and benchmarked at ~234M pairs/s before use.

No p-values are reported: the 437M pairs are massively non-independent (they are
generated by 29,571 items), so any naive per-pair test would be meaningless.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from rapidfuzz import process as rf_process
from rapidfuzz.distance import Levenshtein

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from scripts.ventral_semantic.analyse_and_plot import (              # noqa: E402
    COHORT, EXTRACT, N_WORDS, REPORT, TABLES, sha_file, unit)

BLOCK = 128
LEXICON = "data/lexicon_en_glove_covered.tsv"

VARS = ["D_GloVe", "D_phon", "D_phonN",
        f"D_LTM_s{COHORT[0][0]}", f"D_LTM_s{COHORT[1][0]}",
        f"D_WM_s{COHORT[0][0]}", f"D_WM_s{COHORT[1][0]}"]
K = len(VARS)


def git(*a) -> str:
    return subprocess.run(("git",) + a, cwd=ROOT, capture_output=True,
                          text=True).stdout.strip()


def phoneme_strings(words: List[str]) -> Tuple[List[str], np.ndarray, int]:
    """Map each ARPABET sequence to a string over a private alphabet.

    One phoneme -> one codepoint, so string Levenshtein IS phoneme-sequence
    Levenshtein.  BOS/EOS/PAD never enter: these are the raw lexical forms.
    """
    lex = pd.read_csv(os.path.join(ROOT, LEXICON), sep="\t")
    assert lex["word"].tolist() == words, "lexicon order differs from extraction"
    seqs = [str(a).split() for a in lex["arpabet"]]
    alphabet = sorted({p for s in seqs for p in s})
    assert not ({"<pad>", "<bos>", "<eos>"} & set(alphabet))
    code = {p: chr(0x100 + i) for i, p in enumerate(alphabet)}
    S = ["".join(code[p] for p in s) for s in seqs]
    lens = np.array([len(s) for s in seqs], dtype=np.float32)
    assert lens.min() >= 2 and lens.max() <= 9
    return S, lens, len(alphabet)


class Moments:
    """Exact streaming sufficient statistics for K variables."""

    def __init__(self, k: int):
        self.n = 0
        self.s = np.zeros(k, np.float64)
        self.c = np.zeros((k, k), np.float64)

    def update(self, M: np.ndarray) -> None:      # M: (m, k) float64
        self.n += M.shape[0]
        self.s += M.sum(axis=0)
        self.c += M.T @ M

    def corr(self) -> np.ndarray:
        n = float(self.n)
        mean = self.s / n
        cov = self.c / n - np.outer(mean, mean)
        sd = np.sqrt(np.clip(np.diag(cov), 0.0, None))
        return cov / np.outer(sd, sd)

    def moments(self) -> Dict[str, object]:
        n = float(self.n)
        mean = self.s / n
        cov = self.c / n - np.outer(mean, mean)
        return {"n_pairs": int(self.n), "mean": mean.tolist(),
                "sd": np.sqrt(np.clip(np.diag(cov), 0.0, None)).tolist()}


def main() -> int:
    words = [w for w in
             open(os.path.join(EXTRACT, "lexicon_words.txt")).read().split("\n")
             if w]
    assert len(words) == N_WORDS
    S, lens, n_alpha = phoneme_strings(words)

    bank = np.load(os.path.join(EXTRACT, "glove_bank_normalised.npy"))
    reps = {"D_GloVe": bank}
    for seed, _ in COHORT:
        reps[f"D_LTM_s{seed}"] = unit(
            np.load(os.path.join(EXTRACT, f"s_hat_lexicon_seed{seed}.npy")))
        reps[f"D_WM_s{seed}"] = unit(
            np.load(os.path.join(EXTRACT, f"h_wm_lexicon_seed{seed}.npy")))
    for v in reps.values():
        assert v.shape[0] == N_WORDS
        assert np.allclose(np.linalg.norm(v, axis=1), 1.0, atol=1e-4)
    cos_vars = [v for v in VARS if v not in ("D_phon", "D_phonN")]

    mom = Moments(K)
    cols = np.arange(N_WORDS)
    t0 = time.time()
    for a in range(0, N_WORDS, BLOCK):
        b = min(a + BLOCK, N_WORDS)
        rows = np.arange(a, b)
        mask = cols[None, :] > rows[:, None]      # strict upper triangle
        m = int(mask.sum())
        if m == 0:
            continue
        M = np.empty((m, K), np.float64)
        for v in cos_vars:
            X = reps[v]
            d = 1.0 - (X[a:b] @ X.T)              # (blk, N) cosine distance
            M[:, VARS.index(v)] = d[mask]
        lev = rf_process.cdist(S[a:b], S, scorer=Levenshtein.distance,
                               dtype=np.uint8, workers=-1).astype(np.float32)
        M[:, VARS.index("D_phon")] = lev[mask]
        denom = np.maximum(lens[a:b, None], lens[None, :])
        M[:, VARS.index("D_phonN")] = (lev / denom)[mask]
        mom.update(M)
        if (a // BLOCK) % 40 == 0:
            print(f"  rows {a:6d}/{N_WORDS}  pairs so far {mom.n:,}  "
                  f"({time.time() - t0:.0f}s)", flush=True)

    expected = N_WORDS * (N_WORDS - 1) // 2
    assert mom.n == expected, (mom.n, expected)
    R = mom.corr()
    idx = {v: i for i, v in enumerate(VARS)}
    print(f"\nall {mom.n:,} unique pairs, {time.time() - t0:.0f}s total")

    # ---------------- primary correlation table
    rows_out = []
    for seed, epoch in COHORT:
        for route, key in (("LTM (ventral)", f"D_LTM_s{seed}"),
                           ("WM (dorsal)", f"D_WM_s{seed}")):
            for ref, refkey, kind in (("GloVe (semantic)", "D_GloVe", "primary"),
                                      ("phon raw Levenshtein", "D_phon", "primary"),
                                      ("phon normalised Levenshtein", "D_phonN",
                                       "sensitivity")):
                rows_out.append({
                    "seed": seed, "epoch": epoch, "route": route,
                    "reference": ref, "analysis": kind,
                    "pearson_r": float(R[idx[key], idx[refkey]]),
                    "n_pairs": int(mom.n)})
    rows_out.append({"seed": "-", "epoch": "-", "route": "reference vs reference",
                     "reference": "GloVe vs phon raw", "analysis": "primary",
                     "pearson_r": float(R[idx["D_GloVe"], idx["D_phon"]]),
                     "n_pairs": int(mom.n)})
    rows_out.append({"seed": "-", "epoch": "-", "route": "reference vs reference",
                     "reference": "GloVe vs phon normalised",
                     "analysis": "sensitivity",
                     "pearson_r": float(R[idx["D_GloVe"], idx["D_phonN"]]),
                     "n_pairs": int(mom.n)})
    corr_tbl = pd.DataFrame(rows_out)

    # ---------------- partial RSA: standardized betas from the correlations
    def betas(y: str, p: str) -> Tuple[float, float, float]:
        rys, ryp = R[idx[y], idx["D_GloVe"]], R[idx[y], idx[p]]
        rsp = R[idx["D_GloVe"], idx[p]]
        den = 1.0 - rsp ** 2
        bs = (rys - ryp * rsp) / den
        bp = (ryp - rys * rsp) / den
        r2 = bs * rys + bp * ryp
        return float(bs), float(bp), float(r2)

    reg = []
    for seed, epoch in COHORT:
        for route, key in (("LTM (ventral)", f"D_LTM_s{seed}"),
                           ("WM (dorsal)", f"D_WM_s{seed}")):
            for pk, kind in (("D_phon", "primary"), ("D_phonN", "sensitivity")):
                bs, bp, r2 = betas(key, pk)
                reg.append({"seed": seed, "epoch": epoch, "route": route,
                            "phon_predictor": pk, "analysis": kind,
                            "beta_semantic_glove": bs, "beta_phonological": bp,
                            "model_r2": r2,
                            "predictor_collinearity_r":
                                float(R[idx["D_GloVe"], idx[pk]]),
                            "n_pairs": int(mom.n)})
    reg_tbl = pd.DataFrame(reg)

    os.makedirs(TABLES, exist_ok=True)
    p_corr = os.path.join(TABLES, "rsa_full_lexicon_correlations.tsv")
    p_reg = os.path.join(TABLES, "rsa_full_lexicon_partial_regression.tsv")
    p_mat = os.path.join(TABLES, "rsa_full_lexicon_correlation_matrix.tsv")
    corr_tbl.to_csv(p_corr, sep="\t", index=False)
    reg_tbl.to_csv(p_reg, sep="\t", index=False)
    pd.DataFrame(R, index=VARS, columns=VARS).to_csv(p_mat, sep="\t")

    meta = {
        "phase": "C2 - exact full-lexicon RSA",
        "n_words": N_WORDS, "n_unique_pairs": int(mom.n),
        "pairs_formula": "N(N-1)/2 with N = 29,571",
        "diagonal_excluded": True, "pairs_sampled": False,
        "exactness": ("streaming sufficient statistics (count, sums, "
                      "cross-products) accumulated in float64 over row blocks; "
                      "no dense 29,571 x 29,571 matrix materialised"),
        "block_rows": BLOCK,
        "distances": {
            "D_LTM": "1 - cosine(s_hat_i, s_hat_j), rows L2-normalised",
            "D_WM": "1 - cosine(h_WM_i, h_WM_j), rows L2-normalised",
            "D_GloVe": "1 - cosine(GloVe_i, GloVe_j), bank already normalised",
            "D_phon": "raw Levenshtein on lexical ARPABET sequences (PRIMARY)",
            "D_phonN": "Levenshtein / max(len_i, len_j) (sensitivity only)"},
        "phoneme_sequences": {
            "source": LEXICON, "specials_excluded": ["<pad>", "<bos>", "<eos>"],
            "alphabet_size": n_alpha, "length_range": [2, 9],
            "identical_forms_distance_zero": True},
        "levenshtein_implementation": {
            "library": "rapidfuzz.process.cdist (pre-installed, no new dependency)",
            "scorer": "rapidfuzz.distance.Levenshtein.distance",
            "verified_against_reference_dp": True,
            "benchmark_pairs_per_second": 234_000_000},
        "correlation_metric": "Pearson over all unique pairs",
        "p_values_reported": False,
        "p_value_note": ("437M pairs are generated by 29,571 items and are "
                         "massively non-independent; naive per-pair p-values "
                         "would be meaningless and are deliberately omitted"),
        "cohort": [{"seed": s, "epoch": e} for s, e in COHORT],
        "inputs": {f: sha_file(os.path.join(EXTRACT, f)) for f in
                   ["glove_bank_normalised.npy"]
                   + [f"s_hat_lexicon_seed{s}.npy" for s, _ in COHORT]
                   + [f"h_wm_lexicon_seed{s}.npy" for s, _ in COHORT]},
        "variable_order": VARS,
        "marginal_moments": mom.moments(),
        "outputs": {"correlations": p_corr, "partial_regression": p_reg,
                    "correlation_matrix": p_mat},
        "elapsed_seconds": round(time.time() - t0, 1),
        "model_loaded": False, "inference_run": False,
        "training_performed": False,
        "repository_head": git("rev-parse", "HEAD"),
        "branch": git("rev-parse", "--abbrev-ref", "HEAD"),
    }
    with open(os.path.join(REPORT, "rsa_metadata.json"), "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")

    pd.set_option("display.width", 200)
    print(corr_tbl[corr_tbl.analysis == "primary"].to_string(index=False))
    print()
    print(reg_tbl[reg_tbl.analysis == "primary"][
        ["seed", "route", "beta_semantic_glove", "beta_phonological",
         "model_r2"]].round(4).to_string(index=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
