"""Steps 1 & 2: Audit lexicon_en.tsv and GloVe coverage.

Run before any scale-up training.

Outputs:
    outputs/scale_up_data_audit/lichtheim3_lexicon_audit.json
    outputs/scale_up_data_audit/lichtheim3_lexicon_audit.md
    outputs/scale_up_data_audit/glove_coverage_lexicon_en.json
    outputs/scale_up_data_audit/glove_coverage_lexicon_en.md
    outputs/scale_up_data_audit/missing_glove_words.tsv   (only if GloVe present)

Usage:
    python scripts/audit_lexicon_and_glove.py
    python scripts/audit_lexicon_and_glove.py --lexicon data/lexicon_en.tsv

If data/glove.6B.300d.txt is absent the GloVe section is skipped with a clear
message instructing the user to run:
    bash data/get_glove.sh
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from data.phonemes import build_vocab, PHONEMES

LEX_DEFAULT  = os.path.join(ROOT, "data", "lexicon_en.tsv")
GLOVE_PATH   = os.path.join(ROOT, "data", "glove.6B.300d.txt")
OUT_DIR      = os.path.join(ROOT, "outputs", "scale_up_data_audit")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--lexicon", default=LEX_DEFAULT)
    p.add_argument("--glove",   default=GLOVE_PATH)
    p.add_argument("--out_dir", default=OUT_DIR)
    return p.parse_args()


# ---------------------------------------------------------------------------
# Step 1: lexicon audit
# ---------------------------------------------------------------------------

def audit_lexicon(tsv_path: str, vocab_set: set) -> dict:
    print(f"[audit] Reading {tsv_path} …")
    df = pd.read_csv(tsv_path, sep="\t",
                     names=["rank", "word", "arpabet"],
                     header=0, dtype={"rank": int, "word": str, "arpabet": str})

    n_rows      = len(df)
    rank_min    = int(df["rank"].min())
    rank_max    = int(df["rank"].max())

    # Phoneme length distribution
    df["phones"]  = df["arpabet"].apply(lambda s: s.split())
    df["n_phones"]= df["phones"].apply(len)
    length_dist   = df["n_phones"].value_counts().sort_index().to_dict()

    # Phoneme inventory coverage
    all_phones  = set(p for seq in df["phones"] for p in seq)
    unknown     = sorted(all_phones - vocab_set)
    not_in_lex  = sorted(vocab_set - all_phones)

    # Duplicate words
    dup_words   = df[df.duplicated("word", keep=False)]["word"].tolist()

    # Duplicate phoneme sequences
    df["phones_key"] = df["phones"].apply(tuple)
    dup_phones  = df[df.duplicated("phones_key", keep=False)]["word"].tolist()

    # Lowercase alphabetic check
    non_alpha   = df[~df["word"].str.isalpha()]["word"].tolist()
    non_lower   = df[df["word"] != df["word"].str.lower()]["word"].tolist()

    # Suspicious entries: very short words, very long phoneme sequences
    very_short  = df[df["n_phones"] < 2]["word"].tolist()
    very_long   = df[df["n_phones"] > 9]["word"].tolist()

    report = {
        "lexicon_path":    tsv_path,
        "n_rows":          n_rows,
        "columns":         ["rank", "word", "arpabet"],
        "rank_range":      [rank_min, rank_max],
        "length_distribution": {str(k): v for k, v in length_dist.items()},
        "mean_phoneme_length": round(float(df["n_phones"].mean()), 2),
        "phoneme_inventory": {
            "total_unique_phonemes_in_tsv": len(all_phones),
            "lichtheim3_vocab_size":        len(vocab_set),
            "phonemes_in_tsv_not_in_vocab": unknown,
            "lichtheim3_phonemes_not_in_tsv": not_in_lex,
        },
        "duplicate_words":    len(dup_words),
        "dup_word_examples":  dup_words[:20],
        "duplicate_phoneme_seqs": len(dup_phones),
        "dup_phones_examples":    dup_phones[:20],
        "non_alphabetic_words": len(non_alpha),
        "non_lowercase_words":  len(non_lower),
        "non_alpha_examples":   non_alpha[:20],
        "words_with_n_phones_below_2": len(very_short),
        "words_with_n_phones_above_9": len(very_long),
        "above_9_examples": very_long[:20],
        "availability": {
            "available_10k":  int((df["rank"] <= 10000).sum()),
            "available_20k":  int((df["rank"] <= 20000).sum()),
            "available_30k":  int((df["rank"] <= 30000).sum()),
        },
    }
    print(f"  {n_rows} rows  rank {rank_min}–{rank_max}  "
          f"phoneme lengths {min(length_dist)}-{max(length_dist)}  "
          f"unknown phones: {unknown or 'none'}")
    return report, df


def write_lexicon_audit_md(report: dict, path: str) -> None:
    lines = [
        "# Lichtheim3 Lexicon Audit — `data/lexicon_en.tsv`",
        "",
        f"Generated by `scripts/audit_lexicon_and_glove.py`.",
        "",
        "## Basic statistics",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Path | `{report['lexicon_path']}` |",
        f"| Total rows | {report['n_rows']} |",
        f"| Rank range | {report['rank_range'][0]}–{report['rank_range'][1]} |",
        f"| Mean phoneme length | {report['mean_phoneme_length']} |",
        f"| Duplicate words | {report['duplicate_words']} |",
        f"| Duplicate phoneme sequences | {report['duplicate_phoneme_seqs']} |",
        f"| Non-alphabetic words | {report['non_alphabetic_words']} |",
        f"| Non-lowercase words | {report['non_lowercase_words']} |",
        f"| Words with < 2 phonemes | {report['words_with_n_phones_below_2']} |",
        f"| Words with > 9 phonemes | {report['words_with_n_phones_above_9']} |",
        "",
        "## Phoneme length distribution",
        "",
        "| Length | Count |",
        "|---|---|",
    ]
    for k, v in sorted(report["length_distribution"].items(), key=lambda x: int(x[0])):
        lines.append(f"| {k} | {v} |")

    pi = report["phoneme_inventory"]
    lines += [
        "",
        "## Phoneme inventory",
        "",
        f"- Unique phonemes in TSV: {pi['total_unique_phonemes_in_tsv']}",
        f"- Lichtheim3 vocabulary size: {pi['lichtheim3_vocab_size']}",
        f"- Phonemes in TSV not in vocab: {pi['phonemes_in_tsv_not_in_vocab'] or 'none'}",
        f"- Lichtheim3 phonemes not seen in TSV: {pi['lichtheim3_phonemes_not_in_tsv'] or 'none'}",
        "",
        "## Availability by scale",
        "",
        "| Target scale | Words in TSV with rank ≤ N |",
        "|---|---|",
        f"| 10K | {report['availability']['available_10k']} |",
        f"| 20K | {report['availability']['available_20k']} |",
        f"| 30K | {report['availability']['available_30k']} |",
        "",
        "## Suspicious entries",
        "",
        f"Words above 9 phonemes ({report['words_with_n_phones_above_9']}): "
        f"{report['above_9_examples'] or 'none'}",
        "",
        "> Note: `build_bundled` in `data/lexicon.py` re-applies a "
        "`min_phonemes <= len <= max_phonemes` filter at load time, so even if some",
        "> entries in the TSV exceed the configured max_phonemes=9, they are silently skipped.",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Step 2: GloVe coverage
# ---------------------------------------------------------------------------

def glove_coverage(df: pd.DataFrame, glove_path: str) -> dict:
    print(f"[glove] Loading {glove_path} word index …")
    glove_words: set[str] = set()
    with open(glove_path, "r", encoding="utf-8") as f:
        for line in f:
            word = line.split(" ", 1)[0]
            glove_words.add(word)
    print(f"  {len(glove_words)} GloVe vocab entries loaded")

    df = df.copy()
    df["has_glove"] = df["word"].isin(glove_words)

    n_total    = len(df)
    n_covered  = int(df["has_glove"].sum())
    n_missing  = n_total - n_covered
    pct        = round(100.0 * n_covered / max(n_total, 1), 2)

    missing_df = df[~df["has_glove"]][["rank", "word"]].reset_index(drop=True)

    # Coverage by scale
    cov = {}
    for cap in (1000, 5000, 10000, 20000, 30000):
        sub = df[df["rank"] <= cap]
        cov[str(cap)] = {
            "total":   len(sub),
            "covered": int(sub["has_glove"].sum()),
            "pct":     round(100.0 * sub["has_glove"].sum() / max(len(sub), 1), 2),
        }

    # Maximum N such that all words 1..N have GloVe
    # Sort by rank and find first gap
    sorted_df = df.sort_values("rank")
    max_prefix = 0
    for _, row in sorted_df.iterrows():
        if row["has_glove"]:
            max_prefix = int(row["rank"])
        else:
            break

    report = {
        "glove_path":     glove_path,
        "glove_vocab_size": len(glove_words),
        "n_total":         n_total,
        "n_covered":       n_covered,
        "n_missing":       n_missing,
        "coverage_pct":    pct,
        "coverage_by_scale": cov,
        "max_contiguous_prefix": max_prefix,
        "all_30k_covered": n_missing == 0,
        "first_100_missing": missing_df.head(100).to_dict(orient="records"),
    }
    print(f"  coverage: {n_covered}/{n_total} ({pct}%)  "
          f"max contiguous prefix: {max_prefix}  "
          f"30k all covered: {report['all_30k_covered']}")
    return report, missing_df


def write_glove_coverage_md(report: dict, path: str) -> None:
    lines = [
        "# GloVe Coverage — `data/lexicon_en.tsv`",
        "",
        "Generated by `scripts/audit_lexicon_and_glove.py`.",
        "",
        "## Summary",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| GloVe path | `{report['glove_path']}` |",
        f"| GloVe vocab size | {report['glove_vocab_size']:,} |",
        f"| Lexicon words total | {report['n_total']} |",
        f"| Words with GloVe | {report['n_covered']} |",
        f"| Words WITHOUT GloVe | {report['n_missing']} |",
        f"| Coverage % | {report['coverage_pct']}% |",
        f"| Max contiguous GloVe-covered prefix (ranks 1..N) | {report['max_contiguous_prefix']} |",
        f"| All 30K words have GloVe | {'YES' if report['all_30k_covered'] else 'NO'} |",
        "",
        "## Coverage by target scale",
        "",
        "| Scale (rank ≤ N) | Words | Covered | Coverage % |",
        "|---|---|---|---|",
    ]
    for n, d in report["coverage_by_scale"].items():
        lines.append(f"| {int(n):,} | {d['total']} | {d['covered']} | {d['pct']}% |")

    lines += [
        "",
        "## First 20 missing words",
        "",
        "| Rank | Word |",
        "|---|---|",
    ]
    for item in report["first_100_missing"][:20]:
        lines.append(f"| {item['rank']} | {item['word']} |")

    lines += [
        "",
        f"Full list of {report['n_missing']} missing words: "
        "`outputs/scale_up_data_audit/missing_glove_words.tsv`",
        "",
        "## Recommendation",
        "",
    ]
    if report["all_30k_covered"]:
        lines.append(
            "All 30K words have GloVe embeddings.  "
            "Use `data/lexicon_en.tsv` directly with `--max_words 30000`."
        )
    else:
        n_top = max(
            (int(k) for k, d in report["coverage_by_scale"].items()
             if d["covered"] == d["total"]),
            default=0,
        )
        lines += [
            f"Not all words have GloVe.  Options:",
            f"",
            f"1. **Filtered lexicon** (recommended): use `scripts/create_glove_covered_lexicon.py`",
            f"   to produce `data/lexicon_en_glove_covered.tsv`, then train with",
            f"   `--lexicon_path data/lexicon_en_glove_covered.tsv --max_words 30000`.",
            f"",
            f"2. **Cap at safe prefix**: use `--max_words {report['max_contiguous_prefix']}` "
            f"   (all words 1..{report['max_contiguous_prefix']} have GloVe, but this",
            f"   skips words between ranks {report['max_contiguous_prefix']+1}–30000 that do have GloVe).",
        ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    vocab = build_vocab()
    vocab_set = set(vocab.itos[3:])   # skip PAD/BOS/EOS

    # ---- Step 1: lexicon audit ----
    print("\n=== Step 1: Lexicon audit ===")
    lex_report, df = audit_lexicon(args.lexicon, vocab_set)

    lex_json = os.path.join(args.out_dir, "lichtheim3_lexicon_audit.json")
    with open(lex_json, "w") as f:
        json.dump(lex_report, f, indent=2, default=str)
    print(f"  -> {lex_json}")

    lex_md = os.path.join(args.out_dir, "lichtheim3_lexicon_audit.md")
    write_lexicon_audit_md(lex_report, lex_md)

    # ---- Step 2: GloVe coverage ----
    print("\n=== Step 2: GloVe coverage ===")
    if not os.path.exists(args.glove):
        print(
            f"\n  *** GloVe file NOT FOUND: {args.glove} ***\n"
            "  GloVe is required for scale-up training with real semantic targets.\n"
            "  Run:  bash data/get_glove.sh\n"
            "  Then re-run this script.\n"
            "  (GloVe audit skipped — lexicon audit above is still valid.)"
        )
        return

    glove_report, missing_df = glove_coverage(df, args.glove)

    glove_json = os.path.join(args.out_dir, "glove_coverage_lexicon_en.json")
    with open(glove_json, "w") as f:
        json.dump(glove_report, f, indent=2, default=str)
    print(f"  -> {glove_json}")

    glove_md = os.path.join(args.out_dir, "glove_coverage_lexicon_en.md")
    write_glove_coverage_md(glove_report, glove_md)

    if len(missing_df) > 0:
        miss_tsv = os.path.join(args.out_dir, "missing_glove_words.tsv")
        missing_df.to_csv(miss_tsv, sep="\t", index=False)
        print(f"  -> {miss_tsv}  ({len(missing_df)} words)")

    print("\n=== Audit complete ===")


if __name__ == "__main__":
    main()
