"""Step 3: Create data/lexicon_en_glove_covered.tsv.

Filters data/lexicon_en.tsv to keep only words with a GloVe embedding,
preserving the original rank order and format.  Does NOT overwrite the
original file.

Prerequisites:
    data/glove.6B.300d.txt must exist.
    Run 'bash data/get_glove.sh' first.

Outputs:
    data/lexicon_en_glove_covered.tsv
    outputs/scale_up_data_audit/lexicon_en_glove_covered_report.md

Usage:
    python scripts/create_glove_covered_lexicon.py
"""
from __future__ import annotations

import argparse
import json
import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

LEX_IN      = os.path.join(ROOT, "data", "lexicon_en.tsv")
LEX_OUT     = os.path.join(ROOT, "data", "lexicon_en_glove_covered.tsv")
GLOVE_PATH  = os.path.join(ROOT, "data", "glove.6B.300d.txt")
REPORT_DIR  = os.path.join(ROOT, "outputs", "scale_up_data_audit")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--lexicon_in",  default=LEX_IN)
    p.add_argument("--lexicon_out", default=LEX_OUT)
    p.add_argument("--glove",       default=GLOVE_PATH)
    p.add_argument("--report_dir",  default=REPORT_DIR)
    return p.parse_args()


def main():
    args = parse_args()

    if not os.path.exists(args.glove):
        print(
            f"\n[create_glove_covered_lexicon] ERROR: GloVe not found at {args.glove}\n"
            "Run:  bash data/get_glove.sh\n"
        )
        sys.exit(1)

    print(f"[create_glove_covered_lexicon] Loading GloVe word list from {args.glove} …")
    glove_words: set[str] = set()
    with open(args.glove, "r", encoding="utf-8") as f:
        for line in f:
            glove_words.add(line.split(" ", 1)[0])
    print(f"  {len(glove_words):,} GloVe vocab entries")

    print(f"  Reading {args.lexicon_in} …")
    df = pd.read_csv(args.lexicon_in, sep="\t",
                     names=["rank", "word", "arpabet"],
                     header=0, dtype={"rank": int, "word": str, "arpabet": str})
    n_before = len(df)

    df_covered = df[df["word"].isin(glove_words)].copy()
    n_after    = len(df_covered)
    n_dropped  = n_before - n_after

    # Preserve original rank ordering; do NOT re-rank
    if args.lexicon_out == LEX_IN:
        print("ERROR: --lexicon_out must differ from --lexicon_in to avoid overwriting.")
        sys.exit(1)

    df_covered.to_csv(args.lexicon_out, sep="\t", index=False)
    print(f"  Wrote {n_after} words to {args.lexicon_out}  "
          f"(dropped {n_dropped} without GloVe)")

    # Coverage by scale
    scale_rows = []
    for cap in (10000, 20000, 30000):
        in_sub   = df[df["rank"] <= cap]
        out_sub  = df_covered[df_covered["rank"] <= cap]
        scale_rows.append({
            "target_scale": cap,
            "original_n":   len(in_sub),
            "covered_n":    len(out_sub),
            "dropped_n":    len(in_sub) - len(out_sub),
            "coverage_pct": round(100.0 * len(out_sub) / max(len(in_sub), 1), 2),
        })

    os.makedirs(args.report_dir, exist_ok=True)
    report_path = os.path.join(args.report_dir, "lexicon_en_glove_covered_report.md")
    lines = [
        "# GloVe-Covered Lexicon Report",
        "",
        "Generated by `scripts/create_glove_covered_lexicon.py`.",
        "",
        "## Summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Input lexicon | `{args.lexicon_in}` |",
        f"| Output lexicon | `{args.lexicon_out}` |",
        f"| GloVe source | `{args.glove}` |",
        f"| Words before filter | {n_before} |",
        f"| Words after filter (GloVe-covered) | {n_after} |",
        f"| Words dropped | {n_dropped} |",
        "",
        "## Coverage by training scale",
        "",
        "| Target scale | Original n | Covered n | Dropped | Coverage % |",
        "|---|---|---|---|---|",
    ]
    for r in scale_rows:
        lines.append(
            f"| {r['target_scale']:,} | {r['original_n']} | {r['covered_n']} "
            f"| {r['dropped_n']} | {r['coverage_pct']}% |"
        )
    lines += [
        "",
        "## Usage",
        "",
        "Train with real GloVe embeddings using the filtered lexicon:",
        "",
        "```bash",
        "python scripts/train_checkpoint.py \\",
        f"    --lexicon_path {args.lexicon_out} \\",
        "    --max_words 30000 \\",
        "    --epochs 30 \\",
        "    --seed 0 \\",
        "    --ckpt checkpoints/lichtheim3_30k_glove.pt",
        "```",
        "",
        "If fewer than 30K words are covered, adjust `--max_words` to match `covered_n`",
        "for the target scale.",
        "",
        "> Ranks are preserved from the original `lexicon_en.tsv`.  Frequency ordering",
        "> is unchanged.  No re-numbering is applied.",
    ]
    with open(report_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  -> {report_path}")


if __name__ == "__main__":
    main()
