"""Close the production output manifest by separating concerns.

    python -m scripts.behavioral_analysis.close_production_manifest

The original `production_outputs.sha256` verifies 40/41 because the Phase-7
repository check was appended to `production_execution_log.txt` after the
manifest was written.  Rather than silently rehash the log (which would erase
that history), this splits the manifest in two:

  * production_scientific_outputs_FINAL.sha256 — immutable scientific outputs;
  * production_operational_logs_FINAL.sha256   — append-only operational logs,
    hashed at closure time.

The original manifest is left untouched and marked HISTORICAL / SUPERSEDED in
`manifest_closure_note.md`.  Both final manifests must verify 100 %.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))

from scripts.behavioral_analysis.common import (PRODUCTION_ROOT,      # noqa: E402
                                                REPO_ROOT, repo_relative)

# Append-only operational transcripts: they carry no scientific result.
OPERATIONAL_BASENAMES = {"production_execution_log.txt", "evaluator_stdout.txt"}
SCIENTIFIC_SUFFIXES = (".tsv", ".json", ".md", ".sha256")


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


def classify(root: str):
    scientific, operational, skipped = [], [], []
    for dirpath, _dirs, files in os.walk(root):
        for fn in sorted(files):
            p = os.path.join(dirpath, fn)
            rel = repo_relative(p)
            if fn in OPERATIONAL_BASENAMES:
                operational.append(rel)
            elif fn.endswith(".py") or fn.endswith(".pyc"):
                skipped.append(rel)          # code lives in git, not manifests
            elif fn.startswith("production_scientific_outputs_FINAL") \
                    or fn.startswith("production_operational_logs_FINAL"):
                skipped.append(rel)          # the manifests themselves
            elif fn.endswith(SCIENTIFIC_SUFFIXES):
                scientific.append(rel)
            else:
                skipped.append(rel)
    return sorted(scientific), sorted(operational), sorted(skipped)


def write_manifest(paths, out_path: str) -> None:
    lines = [f"{sha256(os.path.join(REPO_ROOT, rel))}  {rel}" for rel in paths]
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--production_root", default=PRODUCTION_ROOT)
    args = ap.parse_args(argv)
    ctrl = os.path.join(args.production_root, "_control")
    sci, ops, skipped = classify(args.production_root)

    sci_path = os.path.join(ctrl, "production_scientific_outputs_FINAL.sha256")
    ops_path = os.path.join(ctrl, "production_operational_logs_FINAL.sha256")
    write_manifest(sci, sci_path)
    write_manifest(ops, ops_path)
    print(f"-> {repo_relative(sci_path)} ({len(sci)} files)")
    print(f"-> {repo_relative(ops_path)} ({len(ops)} files)")
    if skipped:
        print(f"   ({len(skipped)} files excluded: driver code and the "
              f"manifests themselves)")

    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"],
                                         cwd=REPO_ROOT).decode().strip()
    except Exception:
        commit = "unknown"
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
    note = os.path.join(ctrl, "manifest_closure_note.md")
    with open(note, "w") as f:
        f.write(f"""# Production manifest closure

**Closed**: {stamp}
**Regenerated by**: `scripts/behavioral_analysis/close_production_manifest.py`
**Repository commit at closure**: `{commit}`

## Why the original manifest reports 40/41

`_control/finalize_production.py` walked the production tree and wrote
`production_outputs.sha256` **before** the Phase-7 repository-check section was
appended to `production_execution_log.txt`. The log therefore grew after it had
been hashed. It is an append-only operational transcript of commands, exit
codes and status lines.

**No scientific output file ever changed.** Every item-level prediction table,
enriched table, `metrics.json`, enrichment report, per-seed validation report,
run manifest, cross-seed validation and production summary verifies
byte-identical against the original manifest, and did so again at closure.

## What supersedes it

| Manifest | Scope | Status |
|---|---|---|
| `production_outputs.sha256` | original whole-tree snapshot | **HISTORICAL / SUPERSEDED** — retained unmodified |
| `production_scientific_outputs_FINAL.sha256` | {len(sci)} immutable scientific outputs | authoritative |
| `production_operational_logs_FINAL.sha256` | {len(ops)} append-only operational logs, hashed at closure | authoritative as of the closure timestamp |

Splitting the two is the point: scientific outputs are immutable and must
verify forever, whereas operational logs are expected to grow and are pinned
only at a stated moment. Rehashing the original manifest in place would have
erased that distinction and the history with it.

## Verification

Both final manifests verify 100 % at closure:

```
shasum -a 256 -c {repo_relative(sci_path)}
shasum -a 256 -c {repo_relative(ops_path)}
```
""")
    print(f"-> {repo_relative(note)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
